// schema.ts — kro SimpleSchema parser and SchemaDoc builder.
//
// Parses kro's SimpleSchema type strings (e.g. "integer | default=2") into
// structured ParsedType objects. Assembles SchemaDoc from a raw RGD K8sObject.
//
// This module has NO React dependencies and NO side effects — pure functions only.
//
// Spec: .specify/specs/020-schema-doc-generator/

import type { K8sObject } from '@/lib/api'

// ── Types ─────────────────────────────────────────────────────────────────

/** Structured representation of a kro SimpleSchema type string. */
export interface ParsedType {
  /** Base type: 'string' | 'integer' | 'boolean' | 'number' | 'object' | 'array' | 'map' */
  type: string
  /** For array types ([]string), the item type. */
  items?: string
  /** For map types (map[K]V), the key type. */
  key?: string
  /** For map types (map[K]V), the value type. */
  value?: string
  /** Default value string, if `| default=X` modifier is present. */
  default?: string
  /** True if `| required` modifier is present. */
  required?: boolean
  /**
   * Allowed values if `| enum=a,b,c` modifier is present.
   * Stored as a comma-separated string (preserves original order).
   * See: https://github.com/pnz1990/kro-ui/issues/60
   */
  enum?: string
  /**
   * Minimum value if `| minimum=N` modifier is present (integer/number fields).
   * See: https://github.com/pnz1990/kro-ui/issues/60
   */
  minimum?: string
  /**
   * Maximum value if `| maximum=N` modifier is present (integer/number fields).
   * See: https://github.com/pnz1990/kro-ui/issues/60
   */
  maximum?: string
}

/** A single spec or status field extracted from spec.schema. */
export interface ParsedField {
  /** Field name. */
  name: string
  /** Raw value string from the schema (SimpleSchema type string or CEL expression). */
  raw: string
  /**
   * Parsed type for spec fields.
   * Undefined for status fields (which carry CEL expressions, not type strings).
   */
  parsedType?: ParsedType
  /** True when this is a status field (value is a CEL expression). */
  isStatus?: boolean
  /**
   * Inferred display type for status fields.
   * 'boolean' if the CEL expression contains a comparison operator, else 'string'.
   */
  inferredType?: string
}

/**
 * Assembled schema documentation for an RGD.
 *
 * Derived entirely from spec.schema — no additional API calls required.
 */
export interface SchemaDoc {
  /** The CRD Kind generated by kro (e.g. "WebApplication"). */
  kind: string
  /** API version string (e.g. "v1alpha1"). */
  apiVersion: string
  /** API group (e.g. "kro.run"). */
  group: string
  /** Parsed spec fields (configurable input fields). */
  specFields: ParsedField[]
  /** Status fields with CEL source expressions. */
  statusFields: ParsedField[]
}

// ── Parsing ───────────────────────────────────────────────────────────────

/**
 * Strip trailing space-separated constraint tokens from a raw default value.
 *
 * kro sometimes writes constraints without a pipe separator, e.g.:
 *   `default="normal" enum=easy,normal,hard`  →  `"normal"`
 *   `default=3 minimum=1 maximum=10`          →  `3`
 *
 * A token is a constraint if it starts with one of the known keywords followed
 * by `=`. We scan from right to left and drop any such trailing tokens.
 */
const CONSTRAINT_KW_PREFIXES = ['enum=', 'minimum=', 'maximum=']

function stripTrailingConstraints(value: string): string {
  const tokens = value.split(' ')
  let end = tokens.length
  while (end > 1) {
    const last = tokens[end - 1]
    // 'required' is a bare keyword (no '='); check exactly.
    // Other constraints all end in '=' so use startsWith.
    if (last === 'required' || CONSTRAINT_KW_PREFIXES.some((p) => last.startsWith(p))) {
      end--
    } else {
      break
    }
  }
  return tokens.slice(0, end).join(' ')
}

/**
 * Parse a kro SimpleSchema type string into a structured ParsedType.
 *
 * Supported formats:
 *   - Primitives: "string", "integer", "boolean", "number"
 *   - Arrays:     "[]string", "[]integer", etc.
 *   - Maps:       "map[string]string", "map[string]integer", etc.
 *   - Modifiers:  "integer | default=2", "string | required"
 *   - Combined:   "string | required | default=foo"
 *   - Constraints:"integer | default=3 | minimum=1 | maximum=10"
 *                 "string | default=normal | enum=easy,normal,hard"
 *
 * Constraint modifiers (enum, minimum, maximum) are stored as separate fields
 * on ParsedType and NEVER merged into the `default` field.
 * See: https://github.com/pnz1990/kro-ui/issues/60
 *
 * Unknown/custom base types are passed through verbatim.
 */
export function parseSimpleSchema(typeStr: string): ParsedType {
  const parts = typeStr.split(' | ')
  const base = parts[0].trim()
  const modifiers = parts.slice(1)

  const parsed: ParsedType = parseBaseType(base)

  for (const mod of modifiers) {
    const trimmed = mod.trim()
    if (trimmed === 'required') {
      parsed.required = true
    } else if (trimmed.startsWith('default=')) {
      // Extract the value after 'default='.
      // kro sometimes emits space-separated constraints within the same segment
      // instead of using pipe separators, e.g.:
      //   `default="normal" enum=easy,normal,hard`
      //   `default=3 minimum=1 maximum=10`
      // Strip any trailing `keyword=...` tokens so they don't leak into the
      // default value. See issue #87 / anti-pattern #60.
      //
      // Additionally, kro stores string defaults with JSON quoting, e.g.
      //   `default="normal"` → raw = `"normal"`
      // The YAML serializer then detects the leading `"` and double-encodes it.
      // Strip surrounding double-quotes from string defaults. See issue #114.
      const raw = trimmed.slice('default='.length)
      const stripped = stripTrailingConstraints(raw)
      parsed.default = stripped.startsWith('"') && stripped.endsWith('"') && stripped.length >= 2
        ? stripped.slice(1, -1)
        : stripped
    } else if (trimmed.startsWith('enum=')) {
      parsed.enum = trimmed.slice('enum='.length)
    } else if (trimmed.startsWith('minimum=')) {
      parsed.minimum = trimmed.slice('minimum='.length)
    } else if (trimmed.startsWith('maximum=')) {
      parsed.maximum = trimmed.slice('maximum='.length)
    }
    // Unrecognized modifiers are silently ignored (forward-compatible)
  }

  return parsed
}

/** Parse the base type portion of a SimpleSchema string (before any `|` modifiers). */
function parseBaseType(base: string): ParsedType {
  // Array: []<type>
  if (base.startsWith('[]')) {
    return { type: 'array', items: base.slice(2) }
  }

  // Map: map[<key>]<value>
  const mapMatch = base.match(/^map\[([^\]]+)\](.+)$/)
  if (mapMatch) {
    return { type: 'map', key: mapMatch[1], value: mapMatch[2] }
  }

  // Primitive or unknown
  return { type: base }
}

// ── Status type inference ─────────────────────────────────────────────────

/**
 * Infer the display type for a status field from its CEL expression.
 *
 * Returns 'boolean' if the expression contains a comparison or logical operator
 * that would produce a boolean result. Returns 'string' otherwise.
 */
export function inferStatusType(celExpr: string): string {
  // Strip ${...} wrapper if present
  const inner = celExpr.replace(/^\$\{(.+)\}$/, '$1').trim()

  // Comparison operators → boolean
  if (/[!=<>]=?/.test(inner) || /\b(==|!=|<=|>=|&&|\|\||!)\b/.test(inner)) {
    return 'boolean'
  }

  return 'string'
}

// ── SchemaDoc builder ─────────────────────────────────────────────────────

/**
 * Build a SchemaDoc from a raw RGD K8sObject.
 *
 * Reads: spec.schema.kind, spec.schema.apiVersion, spec.schema.group,
 *        spec.schema.spec, spec.schema.status
 *
 * FR-001: No additional API call — all data from the already-loaded RGD.
 */
export function buildSchemaDoc(rgd: K8sObject): SchemaDoc {
  const spec = rgd.spec as Record<string, unknown> | undefined
  const schema = (spec?.schema ?? {}) as Record<string, unknown>

  const kind = typeof schema.kind === 'string' ? schema.kind : ''
  const apiVersion =
    typeof schema.apiVersion === 'string' ? schema.apiVersion : 'v1alpha1'
  const group = typeof schema.group === 'string' ? schema.group : 'kro.run'

  const rawSpec = (schema.spec ?? {}) as Record<string, unknown>
  const rawStatus = (schema.status ?? {}) as Record<string, unknown>

  const specFields: ParsedField[] = Object.entries(rawSpec).map(
    ([name, value]) => {
      const raw = typeof value === 'string' ? value : String(value)
      return {
        name,
        raw,
        parsedType: parseSimpleSchema(raw),
      }
    },
  )

  const statusFields: ParsedField[] = Object.entries(rawStatus).map(
    ([name, value]) => {
      const raw = typeof value === 'string' ? value : String(value)
      return {
        name,
        raw,
        isStatus: true,
        inferredType: inferStatusType(raw),
      }
    },
  )

  return { kind, apiVersion, group, specFields, statusFields }
}
