// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build tools

// cmd/dump-fixtures generates upstream kro fixture YAML files into
// test/e2e/fixtures/. Run via:
//
//	make dump-fixtures
//
// Output files are deterministic (no timestamps, no random names) and safe to
// re-run — identical output on every invocation. Re-run after a kro version
// bump to track upstream changes:
//
//	GOPROXY=direct GONOSUMDB="*" go get github.com/kubernetes-sigs/kro@vX.Y.Z
//	make tidy
//	make dump-fixtures
//	git diff test/e2e/fixtures/upstream-*.yaml  # review structural changes
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/yaml"

	krov1alpha1 "github.com/kubernetes-sigs/kro/api/v1alpha1"
	"github.com/kubernetes-sigs/kro/pkg/testutil/generator"
)

const (
	fixturesDir = "test/e2e/fixtures"
	namespace   = "kro-ui-e2e"
	group       = "e2e.kro-ui.dev"
	apiVersion  = "v1alpha1"
)

// apacheHeader is prepended to every generated file.
const apacheHeader = `# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by cmd/dump-fixtures. DO NOT EDIT.
# Re-run "make dump-fixtures" after a kro version bump.
`

// withGroup sets the API group on the schema so generated CRDs land in
// the e2e group instead of the default kro.run group.
func withGroup(g string) generator.ResourceGraphDefinitionOption {
	return func(rgd *krov1alpha1.ResourceGraphDefinition) {
		if rgd.Spec.Schema != nil {
			rgd.Spec.Schema.Group = g
		}
	}
}

// writeFixture marshals obj to YAML, prepends the Apache 2.0 header, and
// writes to path. Overwrites existing files (idempotent).
// If obj is an *krov1alpha1.ResourceGraphDefinition, TypeMeta is injected
// before serialisation so kubectl apply works without a separate apiVersion/kind.
func writeFixture(path string, obj interface{}) error {
	if rgd, ok := obj.(*krov1alpha1.ResourceGraphDefinition); ok {
		rgd.TypeMeta = metav1.TypeMeta{
			APIVersion: krov1alpha1.KRODomainName + "/v1alpha1",
			Kind:       "ResourceGraphDefinition",
		}
	}
	raw, err := yaml.Marshal(obj)
	if err != nil {
		return fmt.Errorf("marshal %s: %w", path, err)
	}
	content := apacheHeader + string(raw)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// writeMultiDocFixture writes multiple objects to a single YAML file
// separated by "---" document markers.
func writeMultiDocFixture(path string, objs ...interface{}) error {
	var sb strings.Builder
	sb.WriteString(apacheHeader)
	for i, obj := range objs {
		if i > 0 {
			sb.WriteString("---\n")
		}
		raw, err := yaml.Marshal(obj)
		if err != nil {
			return fmt.Errorf("marshal doc %d of %s: %w", i, path, err)
		}
		sb.WriteString(string(raw))
	}
	if err := os.WriteFile(path, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// instanceObject builds a bare unstructured CR object.
func instanceObject(kind, name, ns string, spec map[string]interface{}) *unstructured.Unstructured {
	return &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": group + "/" + apiVersion,
			"kind":       kind,
			"metadata": map[string]interface{}{
				"name":      name,
				"namespace": ns,
			},
			"spec": spec,
		},
	}
}

// ── Cartesian forEach ─────────────────────────────────────────────────────────

func buildCartesianForEachRGD() *krov1alpha1.ResourceGraphDefinition {
	return generator.NewResourceGraphDefinition(
		"upstream-cartesian-foreach",
		generator.WithSchema("CartesianApp", apiVersion,
			map[string]interface{}{
				"name":    "string",
				"regions": "[]string",
				"tiers":   "[]string",
			},
			map[string]interface{}{
				"configCount": "${string(size(appConfigs))}",
			},
		),
		withGroup(group),
		generator.WithResourceCollection(
			"appConfigs",
			map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "ConfigMap",
				"metadata": map[string]interface{}{
					"name":      "${schema.spec.name}-${region}-${tier}",
					"namespace": namespace,
				},
				"data": map[string]interface{}{
					"region": "${region}",
					"tier":   "${tier}",
				},
			},
			[]krov1alpha1.ForEachDimension{
				{"region": "${schema.spec.regions}"},
				{"tier": "${schema.spec.tiers}"},
			},
			nil, nil,
		),
	)
}

func buildCartesianForEachInstance() *unstructured.Unstructured {
	return instanceObject("CartesianApp", "upstream-cartesian-foreach", namespace, map[string]interface{}{
		"name":    "upstream-cartesian-foreach",
		"regions": []interface{}{"us-east-1", "eu-west-1"},
		"tiers":   []interface{}{"web", "api"},
	})
}

// ── Resource → Collection dependency ─────────────────────────────────────────

func buildCollectionChainRGD() *krov1alpha1.ResourceGraphDefinition {
	return generator.NewResourceGraphDefinition(
		"upstream-collection-chain",
		generator.WithSchema("CollectionChain", apiVersion,
			map[string]interface{}{
				"name":   "string",
				"values": "[]string",
			},
			nil,
		),
		withGroup(group),
		// baseConfig is a plain NodeTypeResource whose data.enabled field gates
		// the forEach expression of chainedConfigs below.
		generator.WithResource(
			"baseConfig",
			map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "ConfigMap",
				"metadata": map[string]interface{}{
					"name":      "${schema.spec.name}-base",
					"namespace": namespace,
				},
				"data": map[string]interface{}{
					"enabled": "true",
					"prefix":  "chained",
				},
			},
			nil, nil,
		),
		// chainedConfigs is a NodeTypeCollection whose forEach references baseConfig —
		// creating a NodeTypeResource → NodeTypeCollection dependency edge in the DAG.
		generator.WithResourceCollection(
			"chainedConfigs",
			map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "ConfigMap",
				"metadata": map[string]interface{}{
					"name":      "${schema.spec.name}-${val}",
					"namespace": namespace,
				},
				"data": map[string]interface{}{
					"val":    "${val}",
					"prefix": "${baseConfig.data.prefix}",
				},
			},
			[]krov1alpha1.ForEachDimension{
				{"val": "${has(baseConfig.data.enabled) ? schema.spec.values : []}"},
			},
			nil, nil,
		),
	)
}

func buildCollectionChainInstance() *unstructured.Unstructured {
	return instanceObject("CollectionChain", "upstream-collection-chain", namespace, map[string]interface{}{
		"name":   "upstream-collection-chain",
		"values": []interface{}{"alpha", "beta"},
	})
}

// ── Contagious includeWhen ────────────────────────────────────────────────────

func buildContagiousIncludeWhenRGD() *krov1alpha1.ResourceGraphDefinition {
	return generator.NewResourceGraphDefinition(
		"upstream-contagious-include-when",
		generator.WithSchema("ContagiousApp", apiVersion,
			map[string]interface{}{
				"name":         "string",
				"enableParent": "boolean",
			},
			nil,
		),
		withGroup(group),
		// parentDeploy is excluded when enableParent=false.
		generator.WithResource(
			"parentDeploy",
			map[string]interface{}{
				"apiVersion": "apps/v1",
				"kind":       "Deployment",
				"metadata": map[string]interface{}{
					"name":      "${schema.spec.name}-deploy",
					"namespace": namespace,
				},
				"spec": map[string]interface{}{
					"replicas": 1,
					"selector": map[string]interface{}{
						"matchLabels": map[string]interface{}{
							"app": "${schema.spec.name}",
						},
					},
					"template": map[string]interface{}{
						"metadata": map[string]interface{}{
							"labels": map[string]interface{}{
								"app": "${schema.spec.name}",
							},
						},
						"spec": map[string]interface{}{
							"containers": []interface{}{
								map[string]interface{}{
									"name":  "app",
									"image": "nginx:stable-alpine",
								},
							},
						},
					},
				},
			},
			nil,
			[]string{"${schema.spec.enableParent}"},
		),
		// childConfig references ${parentDeploy.metadata.name}, creating a
		// dependency. When parentDeploy is excluded, kro also excludes childConfig
		// (contagious exclusion).
		generator.WithResource(
			"childConfig",
			map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "ConfigMap",
				"metadata": map[string]interface{}{
					"name":      "${schema.spec.name}-config",
					"namespace": namespace,
				},
				"data": map[string]interface{}{
					"deployName": "${parentDeploy.metadata.name}",
				},
			},
			nil, nil,
		),
	)
}

func buildContagiousIncludeWhenInstance() *unstructured.Unstructured {
	return instanceObject("ContagiousApp", "upstream-contagious-include-when", namespace, map[string]interface{}{
		"name":         "upstream-contagious",
		"enableParent": false,
	})
}

// ── Cluster-scoped CR ─────────────────────────────────────────────────────────

func buildClusterScopedRGD() *krov1alpha1.ResourceGraphDefinition {
	return generator.NewResourceGraphDefinition(
		"upstream-cluster-scoped",
		generator.WithSchema("ClusterApp", apiVersion,
			map[string]interface{}{
				"name":            "string",
				"targetNamespace": "string",
			},
			nil,
			generator.WithScope(krov1alpha1.ResourceScopeCluster),
		),
		withGroup(group),
		generator.WithResource(
			"appConfig",
			map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "ConfigMap",
				"metadata": map[string]interface{}{
					"name":      "${schema.spec.name}-config",
					"namespace": "${schema.spec.targetNamespace}",
				},
				"data": map[string]interface{}{
					"name": "${schema.spec.name}",
				},
			},
			nil, nil,
		),
	)
}

// No instance for cluster-scoped — the RGD alone exercises the UI.
// A cluster-scoped CR would need no namespace but also needs the CRD to be
// established first; the RGD object is sufficient to test DAG rendering and
// the "no namespace" instance list behaviour.

// ── NodeTypeExternalCollection ────────────────────────────────────────────────

func buildExternalCollectionRGD() *krov1alpha1.ResourceGraphDefinition {
	return generator.NewResourceGraphDefinition(
		"upstream-external-collection",
		generator.WithSchema("ExternalCollectionApp", apiVersion,
			map[string]interface{}{
				"name":            "string",
				"targetNamespace": "string",
			},
			map[string]interface{}{
				"teamCount": "${string(size(teamConfigs))}",
			},
		),
		withGroup(group),
		// teamConfigs is a NodeTypeExternalCollection — reads all ConfigMaps
		// matching label role=team-config in targetNamespace.
		generator.WithExternalRef(
			"teamConfigs",
			&krov1alpha1.ExternalRef{
				APIVersion: "v1",
				Kind:       "ConfigMap",
				Metadata: krov1alpha1.ExternalRefMetadata{
					Namespace: "${schema.spec.targetNamespace}",
					Selector: &metav1.LabelSelector{
						MatchLabels: map[string]string{"role": "team-config"},
					},
				},
			},
			nil, nil,
		),
		// summary is a plain ConfigMap that references the external collection.
		generator.WithResource(
			"summary",
			map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "ConfigMap",
				"metadata": map[string]interface{}{
					"name":      "${schema.spec.name}-summary",
					"namespace": "${schema.spec.targetNamespace}",
				},
				"data": map[string]interface{}{
					"teamCount": "${string(size(teamConfigs))}",
				},
			},
			nil, nil,
		),
	)
}

func buildExternalCollectionPrereq() []corev1.ConfigMap {
	return []corev1.ConfigMap{
		{
			TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "ConfigMap"},
			ObjectMeta: metav1.ObjectMeta{
				Name:      "team-alpha",
				Namespace: namespace,
				Labels:    map[string]string{"role": "team-config"},
			},
			Data: map[string]string{"team": "alpha", "priority": "1"},
		},
		{
			TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "ConfigMap"},
			ObjectMeta: metav1.ObjectMeta{
				Name:      "team-beta",
				Namespace: namespace,
				Labels:    map[string]string{"role": "team-config"},
			},
			Data: map[string]string{"team": "beta", "priority": "2"},
		},
	}
}

func buildExternalCollectionInstance() *unstructured.Unstructured {
	return instanceObject("ExternalCollectionApp", "upstream-ext-coll", namespace, map[string]interface{}{
		"name":            "upstream-ext-coll",
		"targetNamespace": namespace,
	})
}

// ── CEL two-variable comprehensions ──────────────────────────────────────────

func buildCelComprehensionsRGD() *krov1alpha1.ResourceGraphDefinition {
	return generator.NewResourceGraphDefinition(
		"upstream-cel-comprehensions",
		generator.WithSchema("CelComprehensionsApp", apiVersion,
			map[string]interface{}{
				"name": "string",
				"items": map[string]interface{}{
					"type": "object",
					"additionalProperties": map[string]interface{}{
						"type": "string",
					},
				},
				"tags": "[]string",
			},
			nil,
		),
		withGroup(group),
		generator.WithResource(
			"output",
			map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "ConfigMap",
				"metadata": map[string]interface{}{
					"name":      "${schema.spec.name}-output",
					"namespace": namespace,
				},
				"data": map[string]interface{}{
					// transformMap: increment each integer value by 10
					"transformedItems": "${schema.spec.items.transformMap(k, v, {k: string(int(v) + 10)})}",
					// transformList: extract values from tags as a comma-joined string
					"tagList": "${schema.spec.tags.transformList(i, v, v).join(',')}",
					// transformMapEntry: build index-to-tag map from tags list
					"tagIndex": "${schema.spec.tags.transformMapEntry(i, v, string(i), v)}",
				},
			},
			nil, nil,
		),
	)
}

func buildCelComprehensionsInstance() *unstructured.Unstructured {
	return instanceObject("CelComprehensionsApp", "upstream-cel-comp", namespace, map[string]interface{}{
		"name":  "upstream-cel-comp",
		"items": map[string]interface{}{"a": "1", "b": "2"},
		"tags":  []interface{}{"go", "kro"},
	})
}

// ── main ──────────────────────────────────────────────────────────────────────

func main() {
	dir := fixturesDir
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}

	type job struct {
		name string
		fn   func() error
	}

	jobs := []job{
		{"upstream-cartesian-foreach-rgd.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-cartesian-foreach-rgd.yaml"), buildCartesianForEachRGD())
		}},
		{"upstream-cartesian-foreach-instance.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-cartesian-foreach-instance.yaml"), buildCartesianForEachInstance())
		}},
		{"upstream-collection-chain-rgd.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-collection-chain-rgd.yaml"), buildCollectionChainRGD())
		}},
		{"upstream-collection-chain-instance.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-collection-chain-instance.yaml"), buildCollectionChainInstance())
		}},
		{"upstream-contagious-include-when-rgd.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-contagious-include-when-rgd.yaml"), buildContagiousIncludeWhenRGD())
		}},
		{"upstream-contagious-include-when-instance.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-contagious-include-when-instance.yaml"), buildContagiousIncludeWhenInstance())
		}},
		{"upstream-cluster-scoped-rgd.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-cluster-scoped-rgd.yaml"), buildClusterScopedRGD())
		}},
		{"upstream-external-collection-rgd.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-external-collection-rgd.yaml"), buildExternalCollectionRGD())
		}},
		{"upstream-external-collection-prereq.yaml", func() error {
			prereqs := buildExternalCollectionPrereq()
			objs := make([]interface{}, len(prereqs))
			for i := range prereqs {
				objs[i] = prereqs[i]
			}
			return writeMultiDocFixture(filepath.Join(dir, "upstream-external-collection-prereq.yaml"), objs...)
		}},
		{"upstream-external-collection-instance.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-external-collection-instance.yaml"), buildExternalCollectionInstance())
		}},
		{"upstream-cel-comprehensions-rgd.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-cel-comprehensions-rgd.yaml"), buildCelComprehensionsRGD())
		}},
		{"upstream-cel-comprehensions-instance.yaml", func() error {
			return writeFixture(filepath.Join(dir, "upstream-cel-comprehensions-instance.yaml"), buildCelComprehensionsInstance())
		}},
	}

	var errs []string
	for _, j := range jobs {
		if err := j.fn(); err != nil {
			errs = append(errs, fmt.Sprintf("  %s: %v", j.name, err))
		} else {
			fmt.Printf("  wrote %s\n", j.name)
		}
	}

	if len(errs) > 0 {
		fmt.Fprintf(os.Stderr, "dump-fixtures: %d error(s):\n%s\n", len(errs), strings.Join(errs, "\n"))
		os.Exit(1)
	}
	fmt.Printf("dump-fixtures: wrote %d files to %s\n", len(jobs), dir)
}
