// NodeDetailPanel — Right-side inspection panel for a clicked DAG node.
//
// Shows kind, concept explanation per upstream kro node type, and
// CEL expressions highlighted via KroCodeBlock.

import type { DAGNode, NodeType } from '@/lib/dag'
import KroCodeBlock from './KroCodeBlock'
import './NodeDetailPanel.css'

interface NodeDetailPanelProps {
  node: DAGNode
  onClose: () => void
}

/** Human-readable concept explanation per upstream kro node type. */
const CONCEPT_TEXT: Record<NodeType, string> = {
  instance:
    'Root Custom Resource — The CR generated by this RGD. Its spec fields are ' +
    'defined by the schema, and its status is projected from child resource values.',
  resource:
    'Managed Resource — A Kubernetes resource created and owned by kro when an ' +
    'instance of this RGD exists.',
  collection:
    'forEach Collection — A set of Kubernetes resources created by iterating over ' +
    'a CEL expression. Each item produces one resource instance.',
  external:
    'External Reference — A reference to a pre-existing Kubernetes resource. ' +
    'kro reads it but does not create or own it.',
  externalCollection:
    'External Reference Collection — References to pre-existing Kubernetes resources ' +
    'matched by label selector. kro reads them but does not create or own them.',
}

/** Short label for the node type badge. */
const TYPE_LABEL: Record<NodeType, string> = {
  instance: 'Root CR',
  resource: 'Managed Resource',
  collection: 'forEach Collection',
  external: 'External Ref',
  externalCollection: 'External Ref Collection',
}

/** Badge icon per node type. */
const TYPE_ICON: Record<NodeType, string> = {
  instance: '◉',
  resource: '⬜',
  collection: '∀',
  external: '⬡',
  externalCollection: '⬡',
}

/** Render a section with a label and content. */
function Section({
  label,
  children,
}: {
  label: string
  children: React.ReactNode
}) {
  return (
    <div className="node-detail-section">
      <div className="node-detail-section-label">{label}</div>
      {children}
    </div>
  )
}

/**
 * NodeDetailPanel — slide-in panel showing CEL and concept details for a node.
 *
 * Spec: .specify/specs/003-rgd-detail-dag/
 * Opens when a DAG node is clicked. All data comes from the already-loaded RGD.
 */
export default function NodeDetailPanel({ node, onClose }: NodeDetailPanelProps) {
  const conceptText = CONCEPT_TEXT[node.nodeType]
  const typeLabel = TYPE_LABEL[node.nodeType]
  const typeIcon = TYPE_ICON[node.nodeType]

  // Build a YAML-like snippet of the CEL expressions for display
  const celLines: string[] = []
  if (node.readyWhen.length > 0) {
    celLines.push('readyWhen:')
    for (const expr of node.readyWhen) {
      celLines.push(`  - ${expr}`)
    }
  }
  if (node.includeWhen.length > 0) {
    celLines.push('includeWhen:')
    for (const expr of node.includeWhen) {
      celLines.push(`  - ${expr}`)
    }
  }
  if (node.forEach) {
    celLines.push(`forEach: ${node.forEach}`)
  }
  // For root node, show status projections
  if (node.nodeType === 'instance' && node.schemaStatus) {
    const entries = Object.entries(node.schemaStatus)
    if (entries.length > 0) {
      celLines.push('status:')
      for (const [key, val] of entries) {
        celLines.push(`  ${key}: ${String(val)}`)
      }
    }
  }
  const celCode = celLines.join('\n')

  // External ref info
  const extRef = node.externalRef as Record<string, unknown> | undefined
  const extMeta = extRef?.metadata as Record<string, unknown> | undefined

  return (
    <div data-testid="node-detail-panel" className="node-detail-panel">
      {/* Header */}
      <div className="node-detail-header">
        <div className="node-detail-title">
          <span data-testid="node-detail-kind" className="node-detail-kind">
            {node.kind || node.label}
          </span>
          <span className="node-detail-id">{node.id}</span>
        </div>
        <button
          data-testid="node-detail-close"
          className="node-detail-close"
          onClick={onClose}
          aria-label="Close node detail panel"
          type="button"
        >
          ✕
        </button>
      </div>

      {/* Body */}
      <div className="node-detail-body">
        {/* Node type badge */}
        <Section label="Type">
          <div className="node-type-badge-row">
            <span
              className={`node-type-badge node-type-badge--${node.nodeType}`}
            >
              <span>{typeIcon}</span>
              <span>{typeLabel}</span>
            </span>
            {node.isConditional && (
              <span className="node-conditional-badge">
                <span>?</span>
                <span>conditional</span>
              </span>
            )}
          </div>
        </Section>

        {/* Concept explanation */}
        <Section label="Concept">
          <p
            data-testid="node-detail-concept"
            className="node-detail-concept"
          >
            {conceptText}
          </p>
        </Section>

        {/* CEL expressions */}
        {celCode && (
          <Section label="CEL Expressions">
            <KroCodeBlock code={celCode} />
          </Section>
        )}

        {/* External ref details */}
        {(node.nodeType === 'external' || node.nodeType === 'externalCollection') &&
          extRef && (
          <Section label="External Reference">
            <div className="node-detail-extref">
              {extRef.apiVersion != null && <div>apiVersion: {String(extRef.apiVersion)}</div>}
              {extRef.kind != null && <div>kind: {String(extRef.kind)}</div>}
              {extMeta?.name != null && <div>name: {String(extMeta.name)}</div>}
              {extMeta?.namespace != null && <div>namespace: {String(extMeta.namespace)}</div>}
              {extMeta?.selector != null && (
                <div>selector: {JSON.stringify(extMeta.selector)}</div>
              )}
            </div>
          </Section>
        )}

        {/* Schema spec for root node */}
        {node.nodeType === 'instance' && node.schemaSpec && (
          <Section label="Schema Fields">
            <KroCodeBlock
              code={Object.entries(node.schemaSpec)
                .map(([k, v]) => `${k}: ${String(v)}`)
                .join('\n')}
            />
          </Section>
        )}
      </div>
    </div>
  )
}
